apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpd
    app: hr-web-app
  name: webtool

spec:
  containers:
    - image: httpd
      name: webtool
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
