apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
    app: hr-web-app
  name: redis
spec:
  containers:
    - image: redis
      name: redis
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
